spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbo
    username: root
    password: Unicam97!

  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: prodottinobilimarchigiani3@gmail.com
    password: ekfowvoldkmpvkge
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


logging:
  level:
    org.springframework.jdbc.core: DEBUG


token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
server:
  port: 9091


newsletter:
  link:
    facebook: https://www.facebook.com/prodottinobilimarchigianieitaliani
  logo:
    path: image/logo.png
  output:
    path: image/output.jpg

recovery:
  url:
    path: http://localhost:4200/recoverPassword

mail:
  sender:
    name: Prodotti Nobili Marchigiani

portal:
  url: http://localhost:4200